### PR TITLE
Update dota_usermessages.proto

### PR DESCRIPTION
**Pull request by Dmytro4**
adding salutePlayer message

### CODE REVIEW

**Review by spheenik — COMMENTED** [review]
Is this enough? If this message shows up in the replay, shouldn't it also be referenced in `EmbeddedPackets.java`?

**Comment by Dmytro4** [comment]
That messages are about compendium tips so they not should be available in csgo.
Also is there a way to check all messages without changing protobufs? 
Like   ` @OnMessage(DotaUserMessages.?*.class)`
ty

**Comment by spheenik** [comment]
Do these compendium tip messages show up in the replay or not? If so the patch is not enough, since they have to be registered in [EmbeddedPackets.java](https://github.com/skadistats/clarity-protobuf/blob/master/src/main/java/skadistats/clarity/wire/s2/EmbeddedPackets.java).

I don't get what you mean with your second question.

**Comment by Dmytro4** [comment]
sorry, i was away for a week. How i can check without editing protobufs is this event showed in replay or not? I tried this code but it didnt worked out:
` @OnMessage()
    public void onMessage(Context ctx, GeneratedMessage message) {
if(message.toString().indexOf("Salute")>-1)
        count++;
    }`
They for sure saved in replay coz i can see them while viewing a replay in Dota 2 client

**Comment by Dmytro4** [comment]
i even found exact tick number of Tip in some replay by "cl_log_tick 1" in console and i can't see anything readable that even theoretically can be related to tips by next code on tick i needed:
@OnMessage() public void onMessage(Context ctx, GeneratedMessage message) { System.out.printn(message.toString()); }

**Comment by spheenik** [comment]
You would get a warning message of the following kind:
```
unknown embedded message of kind SOURCE2/XXX. Please report this in the corresponding issue: #58
```
with XXX being some number (around 580 I guess)

If you do not get this, these messages are not showing up in the replay, and there's no need to add them to the protobufs. And if they are there, they need to be properly registered in `clarity-protobuf` before one can receive them.

**Comment by Dmytro4** [comment]
i cant see any kind of text that you listed with my last listed code.
I googled your text "unknown embedded message of kind SOURCE2" and found "https://github.com/skadistats/clarity/issues/58"
By messages in this thread i found that everyone runs tick package so i tried this on my replay.
I didnt get any messages but errors about logger that i always had before for months, i fixed logger packages in pom.xml so i can see this messages properly. Then i guess i found what i need - "576".
I can post a message in #58 thread but there was already listed a message "of kind Source2/576".
I added EmbeddedPackets.java to current commit , correct me if im wrong
Thanks!=)

**Comment by spheenik** [comment]
Looks good. Did you test that you got the SalutePlayer message correctly?

**Comment by Dmytro4** [comment]
sorry, but i am a bit dumb and i dont know how to import my own protobufs to my project(

**Pull request merged**
